### PR TITLE
fix: use flags to remove tvOS incompatible types

### LINKED ISSUE #175: tvOS / Apple TV Support
Anybody else hoping to integrate this now?

### PR DESCRIPTION
**Pull request by Krisztiaan**
# Summary 

* What issues does the pull request solve? Please tag them so that they will get automatically closed once the PR is merged

This PR aims to make this library compilable for tvOS. It does not contain other modifications (yet) that would be beneficial for TV, like checking for valid `blurType`s

Resolves #175

* How did you implement the solution?

Use compiler flags for iOS specific blur types

* What areas of the library does it impact?

tvOS compilation

## Test Plan

Build for `tvOS` target

### What's required for testing (prerequisites)?
n/a
### What are the steps to reproduce (after prerequisites)?
n/a
## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| tvOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by ericlifs** [comment]
Tested locally and it works perfectly 👍  I hope this gets merged soon!

Thanks!

**Comment by Krisztiaan** [comment]
Actually the reason that's there is because a couple lines below that's TV specific. What is above seems to fall into the `iOS section`.

**Comment by ericlifs** [comment]
@Krisztiaan yeah technically you are right, but the thing is that `UIBlurEffectStyleRegular` & `UIBlurEffectStyleProminent` do exist on tvOS. The error occurs because it passes the second if validation (it was just a comment)

**Comment by Krisztiaan** [comment]
If you scroll down slightly, you'll see that `TVOS` is already considered. I will however make this more pronounced then.

**Comment by paramaggarwal** [comment]
@ericlifs is wrong. This change is required. Getting errors without it. Thanks for this @Krisztiaan

**Comment by ndillon1** [comment]
Any chance we could get this merged in ? 😬

**Comment by ericlifs** [comment]
Any news on this? This should be merged in

**Comment by Krisztiaan** [comment]
Closing PR on abandoned project.

**Pull request closed without merging**
