### PR TITLE
tvOS support

### PR DESCRIPTION
**Pull request by wouterds**
We're currently using the following changes as a patch on this version and it's working for both AndroidTV & tvOS. Would be great if this could be merged so we can get rid of our patch!

### CODE REVIEW

**Comment by geroale** [comment]
Waiting for the merge too

**Comment by benoitzohar** [comment]
Same here, thanks @wouterds for doing this 🙏

**Comment by Titozzz** [comment]
https://github.com/Kureev/react-native-blur/commit/681a65bc777a05a8aa536b2f73fc99bf452a3202 this is equivalent right ?

**Comment by wouterds** [comment]
> Releasing right now 🥰

Ah that's awesome, good stuff!

**Pull request closed without merging**
