### PR TITLE
Move to Dimezis/BlurView

### LINKED ISSUE #444: Patch file for RN 0.65.+
Since React Native is now officially 0.65.+ version, `jcenter()` was removed from the Android part.
This library relies on [Dimezis/BlurView](https://github.com/Dimezis/BlurView) for Android and the library uses https://jitpack.io/ as stated [here](https://github.com/Dimezis/BlurView#gradle).

So while updating RN for [rnn-starter](https://github.com/kanzitelli/rnn-starter), I have come up with the patch file which you can use with [patch-package](https://github.com/ds300/patch-package).

`@react-native-community+blur+3.6.0.patch`
```
diff --git a/node_modules/@react-native-community/blur/android/build.gradle b/node_modules/@react-native-community/blur/android/build.gradle
index 8177235..5d310b9 100644
--- a/node_modules/@react-native-community/blur/android/build.gradle
+++ b/node_modules/@react-native-community/blur/android/build.gradle
@@ -9,7 +9,6 @@ buildscript {
     if (project == rootProject) {
         repositories {
             google()
-            jcenter()
         }
 
         dependencies {
@@ -37,11 +36,12 @@ android {
 
 repositories {
     google()
-    jcenter()
+
+    maven { url 'https://jitpack.io' }
 }
 
 dependencies {
     //noinspection GradleDynamicVersion
     implementation 'com.facebook.react:react-native:+'
-    implementation 'com.eightbitlab:blurview:1.6.3'
+    implementation 'com.github.Dimezis:BlurView:version-1.6.6'
 }
```

Link to [Gist](https://gist.github.com/kanzitelli/e79bab6dbd6b5117c879eeab31725bf0).
And here are [available versions](https://jitpack.io/#Dimezis/BlurView) of BlurView on jitpack.

### LINKED ISSUE #446: Could not find com.eightbitlab:blurview:1.6.3.
Not able to run the application getting the error

       
      `
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.eightbitlab:blurview:1.6.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - https://repo.maven.apache.org/maven2/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - file:/Users/vin/.m2/repository/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - file:/Users/vin/Desktop/unikapp/node_modules/react-native/android/com/eightbitlab/blurview/1.6.3/blurvie
      `

### PR DESCRIPTION
**Pull request by maxhungry**
Following #444, move to [Dimezis/BlurView](https://github.com/Dimezis/BlurView) and avoid Bintray.

close #444 
close #446

### CODE REVIEW

**Comment by lranches-gemini** [comment]
@Kureev  @maxhungry  Any time frame on when this we'll get merged and released?

**Comment by carl0shd** [comment]
+1, we need this change to support maven users

**Comment by sayurimizuguchi** [comment]
+1 
There was a major downtime at JCenter this past week where all the libs were failing and this was one of them, we need to migrate fully to Maven since JCenter is READ ONLY and people are removing from Gradle dependencies

**Comment by sirpy** [comment]
when can this be merged and released??

**Comment by ShivamJoker** [comment]
@maxhungry can you please release your own version on npm?

**Comment by lranches-gemini** [comment]
+1 would be good to get this merged to unblock Android. This has been sitting for awhile now. Is it possible for someone to create a fork with this commit or something?

**Comment by maxhungry** [comment]
Hey guys, sorry I am not planning to maintain a fork. However, with that said there're a few ways you can consume the fix without a fork:
- reinstalled the package with `yarn add maxhungry/react-native-blur#fix-android-native-dep`
- fork `maxhungry/react-native-blur#fix-android-native-dep` and publish
- copy the change and use great tools like [package-package](https://github.com/ds300/patch-package)

**Comment by Titozzz** [comment]
will be inside #476

**Pull request closed without merging**
