### PR TITLE
added mavenCentral() for gradle builds

### PR DESCRIPTION
**Pull request by maheshwarimrinal**
As jCenter is shutting down so adding mavenCentral() so that gradle builds fail

### CODE REVIEW

**Comment by artyorsh** [comment]
Up ⬆️ 
This will make the library compatible with RN0.65

**Comment by TheWirv** [comment]
It won't because the library used by this package is not available on maven, as per the author: https://github.com/Dimezis/BlurView/issues/134 You could easily add jitpack though, as described on jitpack's front page: https://jitpack.io/

**Comment by kanzitelli** [comment]
@TheWirv thanks for the links! I have created a small patch file for that which uses jitpack at #444

**Review by jvaane — APPROVED** [review]

**Review by BogdanRad — APPROVED** [review]

**Comment by glesperance** [comment]
Any hopes on getting this merged to the main branch & released to npm soon? My builds are failing now.

**Comment by maheshwarimrinal** [comment]
@glesperance you can create patch for now, no one knows how much time it's gonna take :)

**Comment by charpeni** [comment]
Thanks for the ping, @JDMathew!

I should be able to get this released, working on that.

**Comment by JDMathew** [comment]
Amazing, thanks for prioritising this @charpeni

**Comment by jspizziri** [comment]
@charpeni any updates on an npm release?

Thanks!

**Comment by charpeni** [comment]
@jspizziri sorry, I would like to get this out, but things got worse, I lost all my access.

**Pull request merged**
