### PR TITLE
Update BlurViewManagerImpl.java

### PR DESCRIPTION
**Pull request by Gregoirevda**
Only use optimised if hardware acceleration isn't disabled

### CODE REVIEW

**Comment by Gregoirevda** [comment]
fixes #489

**Comment by AdvMaple** [comment]
I tried this, and it work

**Comment by ndekross** [comment]
When is this going to be published?

**Comment by bastianspirek** [comment]
Waiting for this as well.

**Comment by tslater** [comment]
How can we get this thing merged? @Kureev

**Comment by antoinebrtd** [comment]
@Kureev can we merge this as well pls?

**Comment by vinitraj10** [comment]
As a temporary solution until this gets merged, if you all still struggling and want this to be used as a package, i have created a repository and put the bundle there, since we had the same issue and as we work closely with CI/CD, applying patch locally was not a good solution for us, as CI scripts need to be updated to discard the changes every time `yarn` or `npm install` done.

Instead i just moved the patch bundle into a github fork and started using it in our package.json which was much more cleaner solution as it doesn't touch `.gitignore` to ignore few patch files and CI is also happy.

> just forking to git repo and using url might not work as the package is not compiled while forked so you need to bundle it and place in fork if you want to use it that way

You can use our bundle by using the following command

```js
> yarn add 'vinitraj10/react-native-blur'
```
or
```js
npm install 'vinitraj10/react-native-blur'
```

**Comment by mlaythe** [comment]
any update on when this will be merged?

**Comment by jspizziri** [comment]
@Titozzz any chance you could look at this? If not are there other maintainers that could be worked with? Or is this package looking for new maintainers?

**Comment by Titozzz** [comment]
Added a Todo for Tuesday 🙏

**Pull request closed without merging**
