### PR TITLE
Adds library project files

### PR DESCRIPTION
**Pull request by lwansbrough**
Not sure - this might be a pedantic change. I prefer to have the library's project files so the component can be cleanly added and removed from a project.

### CODE REVIEW

**Comment by Kureev** [comment]
Why suggested way isn't good for you? You just right-click on the project name and "Add files to <ProjectName>" (I saw a lot of components do it this way). What's the profit in having xcodeproj for every component? I'm just a junior in iOS development, so I'll be grateful if you can explain it to me.

**Comment by lwansbrough** [comment]
So am I hahah. Blind leading the blind. Uhm, just from my little experience I'd prefer the project file because it provides a nice neat wrapper around your code. Allows me to separate my code from your code. Here's what the changes above look like in an actual project: https://i.imgur.com/2E735Xf.png

**Comment by Kureev** [comment]
Yeah, maybe it's really make sense. But in this case it would be nice to install components via cocoa pods. Give me some time to discuss it with my iOS development team and I'll come back with some feedback about it.

**Comment by lwansbrough** [comment]
I wouldn't focus too much on that - I believe the Facebook team is working on a native component bootstrapper CLI.

**Comment by Kureev** [comment]
Sorry for the late feedback, but still... I talked to my colleagues about your idea, and for such a small projects like this one, we decided it have too much overhead, which we basically don't need. But thanks for your attention and your ideas are always welcome :)

**Pull request closed without merging**
